### ISSUE TITLE
tried to run it empty, got missing table error

### ISSUE THREAD

**Issue by tommy-mor** [adityaathalye/usermanager-first-principles#1]
```SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
Setting up DB having dbname:  dev/usermanager_dev_db.sqlite3
Created database and addressbook table!
Exception: [SQLITE_ERROR] SQL error or missing database (no such table: department)
Unable to populate the initial data -- proceed with caution!
Starting up Server on port:  3000```

**Comment by adityaathalye** [comment]
Ah I see how this can trip up people. I've pushed an update to remove this source of friction. The [commit message](https://github.com/adityaathalye/usermanager-first-principles/commit/1b5f0e276c52a241015317bfa764ebd792ac0b13) explains details.

You can fetch the latest (or just create a dev directory locally) and retry.

Thank you for flagging this! Any other feedback is appreciated too.

**Comment by tommy-mor** [comment]
cool
